# Database
spring:
  application:
    name: bookManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db-bookManager?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 828386
    initialization-mode: always
  api:
    versao: 1.0.0
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update #create-drop #update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    format_sql: true
# JWT
bookManager:
  jwt:
    secret: A+X;fTJP&Pd,TD9dwVq(hsHX,ya^<wsD_UK7L+@=S;{'CydP]{v@}G'b>et;yz$*\yL5S8EJN:%P:X%H9>#nYLrX}@\s?CQcpspH,2emzBc!Q[V'AYa~uzF8WR~AUrMzxp/V$9([S9X#zj/CH('#]B_Hc+%fGhe27YB;^j4\Xk=Ju"Ap~_&<L;=!Z;!,2UP;!hF3P]j85#*`&T]/kB/W^6$v~u6qpejL>kY^f)sy4:qTq_Ec!-z!@aAp~sLKGU>$
    expiration: 86400000
#info:
#  app:
#    name: '@project.name@'
#    version: '@project.version@'